export const doctors = [
  {
    id_doctor: 1,
    name: "Dr. Armando Matheus",
    speciality: "Ginecologista e obstetrícia",
    icon: "M",
  },
  {
    id_doctor: 2,
    name: "Dr. Pedro Martins",
    speciality: "Cardiologista",
    icon: "M",
  },
  {
    id_doctor: 3,
    name: "Dra. Maria Clara",
    speciality: "Dermatologista",
    icon: "F",
  },
  {
    id_doctor: 4,
    name: "Dr. João Ricardo",
    speciality: "Ortopedista",
    icon: "M",
  },
  {
    id_doctor: 5,
    name: "Dra. Fernanda Souza",
    speciality: "Oftalmologista",
    icon: "F",
  },
  {
    id_doctor: 6,
    name: "Dr. Luiz Henrique",
    speciality: "Endocrinologista",
    icon: "M",
  },
  {
    id_doctor: 7,
    name: "Dra. Paula Vieira",
    speciality: "Pediatra",
    icon: "F",
  },
  {
    id_doctor: 8,
    name: "Dr. Antônio Carlos",
    speciality: "Neurologista",
    icon: "M",
  },
  {
    id_doctor: 9,
    name: "Dra. Bruna Lima",
    speciality: "Psiquiatra",
    icon: "F",
  },
  {
    id_doctor: 10,
    name: "Dr. Renato Gomes",
    speciality: "Urologista",
    icon: "M",
  },
  {
    id_doctor: 11,
    name: "Dra. Juliana Pereira",
    speciality: "Otorrinolaringologista",
    icon: "F",
  },
  {
    id_doctor: 12,
    name: "Dra. Nise da Silveira",
    speciality: "Cirurgia plastica",
    icon: "F",
  },
];

export const appointments = [
  {
    id_appoitment: 1,
    service: "Consulta",
    doctor: "Dra. Nise da Silveira",
    speciality: "Cirurgia plastica",
    booking_date: "2024-10-25",
    booking_hour: "08:30",
  },
  {
    id_appoitment: 2,
    service: "Consulta",
    doctor: "Dr. Pedro Martins",
    speciality: "Cardiologista",
    booking_date: "2024-10-26",
    booking_hour: "10:00",
  },
  {
    id_appoitment: 3,
    service: "Exame",
    doctor: "Dra. Maria Clara",
    speciality: "Dermatologista",
    booking_date: "2024-10-27",
    booking_hour: "11:30",
  },
  {
    id_appoitment: 4,
    service: "Consulta",
    doctor: "Dr. João Ricardo",
    speciality: "Ortopedista",
    booking_date: "2024-10-28",
    booking_hour: "09:00",
  },
  {
    id_appoitment: 5,
    service: "Consulta",
    doctor: "Dra. Fernanda Souza",
    speciality: "Oftalmologista",
    booking_date: "2024-10-29",
    booking_hour: "15:00",
  },
  {
    id_appoitment: 6,
    service: "Exame",
    doctor: "Dr. Luiz Henrique",
    speciality: "Endocrinologista",
    booking_date: "2024-10-30",
    booking_hour: "13:00",
  },
  {
    id_appoitment: 7,
    service: "Consulta",
    doctor: "Dra. Paula Vieira",
    speciality: "Pediatra",
    booking_date: "2024-10-31",
    booking_hour: "14:30",
  },
  {
    id_appoitment: 8,
    service: "Consulta",
    doctor: "Dr. Antônio Carlos",
    speciality: "Neurologista",
    booking_date: "2024-11-01",
    booking_hour: "12:00",
  },
  {
    id_appoitment: 9,
    service: "Consulta",
    doctor: "Dra. Bruna Lima",
    speciality: "Psiquiatra",
    booking_date: "2024-11-02",
    booking_hour: "16:30",
  },
  {
    id_appoitment: 10,
    service: "Exame",
    doctor: "Dr. Renato Gomes",
    speciality: "Urologista",
    booking_date: "2024-11-03",
    booking_hour: "17:00",
  },
  {
    id_appoitment: 11,
    service: "Consulta",
    doctor: "Dra. Juliana Pereira",
    speciality: "Otorrinolaringologista",
    booking_date: "2024-11-04",
    booking_hour: "08:00",
  },
];
